# CREATING A DATAFRAME FROM AN ARRAY:

# 1.Using Array:
     1.Numpy array
     2.python list

# 2.Dictionary:
    Here the keys are features and values are data and they are known as series

# 3.CSV files:
    Easiest way to create a dataframe

In [1]:
import pandas as pd
import numpy as np

# 1 Craeting a dataframe from an array

# 1.1 Option 1

In [4]:
#Creating an array
data = np.array([[1,2],[2,3],[4,5]])
data

array([[1, 2],
       [2, 3],
       [4, 5]])

In [5]:
#Creating a data frame
pd.DataFrame(data)

   0  1
0  1  2
1  2  3
2  4  5

In [8]:
#renaming the index and column
DataFrame=pd.DataFrame(data,index=["Row1","Row2","Row3"],columns=["Col1","Col2"])

In [9]:
#visualizing the data frame
DataFrame

      Col1  Col2
Row1     1     2
Row2     2     3
Row3     4     5

# Next
Using list

In [10]:
data = [[1,2],[2,3],[4,5]]

In [11]:
DataFrame=pd.DataFrame(data,index=["Row1","Row2","Row3"],columns=["Col1","Col2"])

In [12]:
DataFrame

      Col1  Col2
Row1     1     2
Row2     2     3
Row3     4     5

2.Creating a DataFrame from a dictionary

In [13]:
# lists used for this example
states = ["California","Texas","Florida","New York"]
population = [3892386,578269,90728822,1878799]

In [14]:
#storing lists within a dictionary
dict_states = {"states":states,"population":population}

In [17]:
#Creating the dataframe
df_population = pd.DataFrame(dict_states)

In [18]:
#showing the dataframe
df_population

       states  population
0  California     3892386
1       Texas      578269
2     Florida    90728822
3    New York     1878799

3.Creating a DataFame from a csv file

In [22]:
# reading the csv file
Youtube_dataset=pd.read_csv(r"/content/youtube_4k_channels_cleaned.csv")

In [24]:
Youtube_dataset.head()

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description,Views per Subscriber,Views per Video,Subscribers (M),Views (B),Tier
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,116005659874,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...,244.74,121344833.0,474.0,116.006,🔴 100M+
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,335650634349,25757,IN,"Music can change the world"". T-Series is India...",1079.26,13031434.0,311.0,335.651,🔴 100M+
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,187185678767,168366,IN,Sony Entertainment Television is one of the le...,995.67,1111778.0,188.0,187.186,🔴 100M+
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,120113700862,1005,US,“Vlad & Niki” is the global preschool phenomen...,806.13,119516120.0,149.0,120.114,🔴 100M+
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,123546449303,1589,US,"Welcome to Diana and Roma world - where Diana,...",895.26,77751069.0,138.0,123.546,🔴 100M+

When I use this csv in jupter notebook the dataset should be present in the same directory where our jupyter notebook script is located.

In [25]:
Youtube_dataset=pd.read_csv(r"/content/youtube_4k_channels_cleaned.csv")